### ISSUE TITLE
Broken example 'collections/tree'

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/fyr#1]
The tree implementation seems broken right now.
The Compiler throws the following message:
`<path>/fyr/src/collections/tree/tree.fyr (174,33): The expression is not mutable, because the variable is not mutable or the type is const`

I'm not entirely sure if it's an issue in the implementation or the compiler.
@weistn could you have a look at this?

**Comment by weistn** [comment]
I have no compiler here, but it should be `var` instead of `let`.

The compiler is right, because the for loop would assign multiple times to `i`, which is not allowed when `let` is used.

**Comment by OskarCarl** [comment]
Okay, I've changed it. It seems like this part is currently missing in the compiler as it generates an
```
ImplementationError: lock_arr
    at CBackend.emitExprIntern (/home/oskar/Documents/Work/fyr/lib/backend/backend_c.js:1533:15)
```

**Comment by weistn** [comment]
Fixed
