### ISSUE TITLE
A computer language should not be implemented in NodeJS

### ISSUE THREAD

**Issue by yurivict** [vs-ude/fyr#3]
```NodeJS```, in order to install a program, performs direct downloads from GitHub. It is extremely hard or impossible to create a package for a NodeJS project such that it doesn't perform downloads during the the package creation process. So, I if I am concerned about some random github accounts being hijacked and malware being streamed to my systems without me knowing this, I should not use ```FurLang```.

**Comment by OskarCarl** [comment]
npm does not download the package from GitHub. They are fetched from npmjs.com.
The packages provided by us (aside from Homebrew) do not download the GitHub source to your computer.  
Once the package is installed, the compiler works completely offline.

The language itself is not hosted on NodeJS. Once the sources are compiled, they are as much a native package as anything else compiled by GCC (which we utilize to do so). 

I honestly do not see your point, as anything you download from the internet might be compromised, you have to place your trust somewhere.

Is there anything you would like to contribute to this project with your comment? If not, I would like to close it.

**Comment by OskarCarl** [comment]
During the packaging process, downloads are more or less required. That much is true.
The downloads do not fetch from GitHub, though.

**Comment by yurivict** [comment]
npm feeds its packages from github, often in real time, which is the same thing.

I've spent a considerable time and effort trying to package NodeJS projects in a safe way, at least not having it downloading the latest versions of various packages, and this proved to be impossible.

This is why NodeJS is fundamentally unsafe as it is, and if some language is implemented in NodeJS this makes this language unsafe too.

**Comment by OskarCarl** [comment]
I can understand that, but a project built in C might just as well be compromised.
You can inspect it before building but with large projects that might become unfeasible.

The final Fyr compiler is built on top of three dependencies without any second level dependencies.
This is more accessible to read, and can be inspected even after the package was built.
I don't want to say that this is good, but I don't see how it's worse than, say, [GCC](https://github.com/gcc-mirror/gcc).

Requiring an internet connection while building is not optimal, but I don't think its a huge risk.

And I have not yet seen a way to build an npm package that rebuilds itself on pulls, in real time.

**Comment by yurivict** [comment]
A C++ project usually builds from one repository. It is inspected by the project maintainer once, and then at later times it can be re-built predictably. Sure, the maintainer can make a mistake, and pass some malware, but at least this mistake can be identified and traced to a person/a place.

A NodeJS project can't be rebuilt predictably, because it almost always downloads latest versions of a lot of packages. This is my concern. So I just can't create a FreeBSD package for furlang even if wanted. Malware in a NodeJS project can come and go undetected, without much traceability.

This is why there is not a single NodeJS-based port or package on BSDs, because such package can't be made safe.

**Comment by yurivict** [comment]
In short, NodeJS is a fundamentally insecure technology, compared to other technological options.

**Comment by OskarCarl** [comment]
Then we sadly cannot have a FreeBSD package for now.
A rewrite is definitely out of scope at this point in time and our resources are dedicated to issues we deem more important right now.
Thanks for your clarification.

**Comment by yurivict** [comment]
Ok, thanks.
